object Versions {
    const val compose = "1.5.3"
    const val composeMaterial = "1.1.2"
    const val kotlin = "1.9.10" //Compatibility with compose
    const val gradle = "8.3.0-alpha07"
    const val gradleDifferentSquema = "8.3.0-alpha-7"
    const val googleServices = "4.3.0"
    const val crashlyticsGradle = "2.9.1"
    const val performanceGradle = "1.4.1"
    const val hiltGradle = "2.48.1"
    const val firebase = "30.2.0"
    const val hilt = "2.48.1"
    const val junit = "4.13.2"
    const val extJunit = "1.1.3"
    const val expressoCore = "3.4.0"
    const val androidXCore = "1.8.0"
    const val androidXLifecyle = "2.6.0-alpha01"
    const val androidXNavitationCompose = "2.7.4"
    const val androidXHiltNavitationCompose = "1.0.0"
    const val androidXSplashScreen = "1.0.0-rc01"
    const val room = "2.4.2"
    const val coroutines = "1.6.3"
    const val ksp = "1.9.10-1.0.13"
    const val composeNavigationAnimation = "0.32.0"

}
