object Versions {
    const val compose = "1.1.1"
    const val composeMaterial = "1.0.0-alpha13"
    const val kotlin = "1.6.10"
    const val gradle = "7.4.0-alpha05"
    const val googleServices = "4.3.0"
    const val crashlyticsGradle = "2.9.0"
    const val performanceGradle = "1.4.1"
    const val hiltGradle = "2.38.1"
    const val firebase = "30.1.0"
    const val hilt = "2.42"
    const val junit = "4.13.2"
    const val extJunit = "1.1.3"
    const val expressoCore = "3.4.0"
    const val androidXCore = "1.8.0"
    const val androidXLifecyle = "2.4.1"
    const val androidXSplashScreen = "1.0.0-rc01"
    const val room = "2.4.2"
    const val coroutines = "1.6.3"
}
